name: Build and deploy LaTeX document

on:
  push:
    branches:
      - rapport-src
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        
      - name: Compile "rapport modelisation"
        uses: xu-cheng/latex-action@v2
        with:
          root_file: rapport.tex
          working_directory : rapport_modelisation/rapport
          
      - name: Compile "annexe modelisation"
        uses: xu-cheng/latex-action@v2
        with:
          root_file: annexe.tex
          working_directory : rapport_modelisation/annex_use_case
          
      - name: Compile "rapport implementation"
        uses: xu-cheng/latex-action@v2
        with:
          root_file: rapport.tex
          working_directory : rapport_implementation/rapport
            
      - name: Release PDF files
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "rapport-implementation"
          prerelease: false
          title: "Rapport implémentation"
          files: |
            rapport_implementation/rapport/rapport.pdf
          
      - name: Release PDF files
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "rapport-modelisation"
          prerelease: false
          title: "Rapport modélisation"
          files: |
            rapport_modelisation/rapport/rapport.pdf
            rapport_modelisation/annex_use_case/annexe.pdf
